import type { Lead } from "@/lib/types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    workspaceId: "ws_1",
    company: "TechFlow Solutions",
    website: "techflow.io",
    industry: "SaaS",
    companySize: "11–50",
    country: "United States",
    city: "San Francisco",
    contactName: "Sarah Chen",
    contactTitle: "CEO & Co-founder",
    email: "sarah@techflow.io",
    phone: "+1 415 555 0192",
    whatsapp: "+1 415 555 0192",
    linkedin: "linkedin.com/in/sarahchen",
    painPoints: ["Slow lead generation", "Manual outreach", "No CRM system"],
    icebreaker: "Noticed TechFlow recently expanded to enterprise clients — congrats on the Series A!",
    outreachAngle: "Show ROI of AI automation vs manual SDR — could save 40 hrs/week",
    estimatedValue: "$8,000 – $15,000",
    leadScore: 92,
    aiConfidence: 88,
    stage: "NEW",
    tags: ["hot-lead", "enterprise"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-24T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-24T09:00:00Z").toISOString(),
  },
  {
    id: "2",
    workspaceId: "ws_1",
    company: "Pixel Studio Agency",
    website: "pixelstudio.co",
    industry: "Design Agency",
    companySize: "1–10",
    country: "United Kingdom",
    city: "London",
    contactName: "James Whitfield",
    contactTitle: "Founder",
    email: "james@pixelstudio.co",
    phone: "+44 20 7946 0958",
    whatsapp: "+44 20 7946 0958",
    linkedin: "linkedin.com/in/jameswhitfield",
    painPoints: ["Losing clients to bigger agencies", "No lead pipeline", "Manual invoicing"],
    icebreaker: "Loved the rebrand you did for Luminary Foods — the typography was stunning.",
    outreachAngle: "Help them build a client acquisition system so they stop relying on referrals",
    estimatedValue: "$3,500 – $7,000",
    leadScore: 78,
    aiConfidence: 82,
    stage: "CONTACT_READY",
    tags: ["agency", "design"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-23T11:30:00Z").toISOString(),
    updatedAt: new Date("2026-06-25T14:00:00Z").toISOString(),
  },
  {
    id: "3",
    workspaceId: "ws_1",
    company: "GreenCart E-commerce",
    website: "greencart.shop",
    industry: "E-commerce",
    companySize: "11–50",
    country: "Canada",
    city: "Toronto",
    contactName: "Priya Kapoor",
    contactTitle: "Head of Marketing",
    email: "priya@greencart.shop",
    phone: "+1 416 555 0381",
    whatsapp: "+1 416 555 0381",
    linkedin: "linkedin.com/in/priyakapoor",
    painPoints: ["High cart abandonment", "Low email open rates", "No personalization"],
    icebreaker: "GreenCart's sustainability mission is inspiring — saw you hit 50k customers!",
    outreachAngle: "AI-personalized email sequences to recover abandoned carts",
    estimatedValue: "$5,000 – $12,000",
    leadScore: 85,
    aiConfidence: 79,
    stage: "EMAIL_SENT",
    tags: ["ecommerce", "email"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-22T08:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-25T10:00:00Z").toISOString(),
  },
  {
    id: "4",
    workspaceId: "ws_1",
    company: "MedSync Healthcare",
    website: "medsync.io",
    industry: "Healthcare Tech",
    companySize: "51–200",
    country: "United States",
    city: "Austin",
    contactName: "Dr. Marcus Reed",
    contactTitle: "CTO",
    email: "marcus@medsync.io",
    phone: "+1 512 555 0247",
    whatsapp: "+1 512 555 0247",
    linkedin: "linkedin.com/in/drmarcusreed",
    painPoints: ["Patient data fragmentation", "Slow onboarding", "No developer APIs"],
    icebreaker: "MedSync's HIPAA-first approach is exactly what the market needs right now.",
    outreachAngle: "Build custom integrations between their platform and EHR systems",
    estimatedValue: "$20,000 – $50,000",
    leadScore: 88,
    aiConfidence: 91,
    stage: "REPLIED",
    tags: ["healthcare", "enterprise", "high-value"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-20T07:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-26T09:00:00Z").toISOString(),
  },
  {
    id: "5",
    workspaceId: "ws_1",
    company: "Launchpad Ventures",
    website: "launchpadvc.com",
    industry: "Venture Capital",
    companySize: "1–10",
    country: "United States",
    city: "New York",
    contactName: "Alexandra Torres",
    contactTitle: "Managing Partner",
    email: "alex@launchpadvc.com",
    phone: "+1 212 555 0194",
    whatsapp: "+1 212 555 0194",
    linkedin: "linkedin.com/in/alexandratorres",
    painPoints: ["Portfolio monitoring is manual", "No deal flow CRM", "LP reporting is slow"],
    icebreaker: "Your recent exit with NovaTech was impressive — 8x return in 3 years.",
    outreachAngle: "Custom deal flow & portfolio management dashboard for VCs",
    estimatedValue: "$15,000 – $30,000",
    leadScore: 74,
    aiConfidence: 76,
    stage: "MEETING_SCHEDULED",
    tags: ["vc", "fintech", "high-value"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-18T10:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-26T11:00:00Z").toISOString(),
  },
  {
    id: "6",
    workspaceId: "ws_1",
    company: "Shopify Plus Store — Luxe Threads",
    website: "luxethreads.com",
    industry: "Fashion E-commerce",
    companySize: "11–50",
    country: "Australia",
    city: "Sydney",
    contactName: "Olivia Park",
    contactTitle: "Operations Director",
    email: "olivia@luxethreads.com",
    phone: "+61 2 9876 5432",
    whatsapp: "+61 2 9876 5432",
    linkedin: "linkedin.com/in/oliviapark",
    painPoints: ["Inventory sync issues", "Multi-currency complexity", "High return rate"],
    icebreaker: "Luxe Threads just crossed 100k Instagram followers — the aesthetics are on point!",
    outreachAngle: "Custom Shopify automation for inventory and returns management",
    estimatedValue: "$6,000 – $14,000",
    leadScore: 81,
    aiConfidence: 84,
    stage: "PROPOSAL_SENT",
    tags: ["shopify", "fashion", "ecommerce"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-15T06:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-25T16:00:00Z").toISOString(),
  },
  {
    id: "7",
    workspaceId: "ws_1",
    company: "DevHive SaaS",
    website: "devhive.app",
    industry: "Developer Tools",
    companySize: "1–10",
    country: "Germany",
    city: "Berlin",
    contactName: "Lukas Becker",
    contactTitle: "Co-founder & CEO",
    email: "lukas@devhive.app",
    phone: "+49 30 5550 9283",
    whatsapp: "+49 30 5550 9283",
    linkedin: "linkedin.com/in/lukasbecker",
    painPoints: ["No marketing automation", "Manual onboarding", "Churn is rising"],
    icebreaker: "DevHive's CLI tooling concept is brilliant — saw it trending on Hacker News!",
    outreachAngle: "Build onboarding email sequences and churn prevention automations",
    estimatedValue: "$4,000 – $9,000",
    leadScore: 69,
    aiConfidence: 72,
    stage: "NEGOTIATION",
    tags: ["saas", "developer-tools"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-10T12:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-26T08:00:00Z").toISOString(),
  },
  {
    id: "8",
    workspaceId: "ws_1",
    company: "Coastal Property Group",
    website: "coastalpg.com",
    industry: "Real Estate",
    companySize: "11–50",
    country: "United States",
    city: "Miami",
    contactName: "Roberto Díaz",
    contactTitle: "CEO",
    email: "roberto@coastalpg.com",
    phone: "+1 305 555 0132",
    whatsapp: "+1 305 555 0132",
    linkedin: "linkedin.com/in/robertodiaz",
    painPoints: ["Lead follow-up is manual", "No CRM", "Agents not converting"],
    icebreaker: "Coastal PG's waterfront listings in Brickell are absolutely premium.",
    outreachAngle: "AI-powered lead nurturing system for real estate agents",
    estimatedValue: "$7,000 – $18,000",
    leadScore: 77,
    aiConfidence: 80,
    stage: "WON",
    tags: ["real-estate", "won"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-01T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-20T17:00:00Z").toISOString(),
  },
  {
    id: "9",
    workspaceId: "ws_1",
    company: "NovaSpark Marketing",
    website: "novaspark.io",
    industry: "Marketing Agency",
    companySize: "1–10",
    country: "India",
    city: "Bangalore",
    contactName: "Ananya Sharma",
    contactTitle: "Founder",
    email: "ananya@novaspark.io",
    phone: "+91 98765 43210",
    whatsapp: "+91 98765 43210",
    linkedin: "linkedin.com/in/ananyasharma",
    painPoints: ["Client reporting is manual", "No white-label dashboard", "Losing to bigger agencies"],
    icebreaker: "NovaSpark's case study on scaling Zomato's influencer campaigns was really impressive.",
    outreachAngle: "White-label analytics dashboard for digital marketing agencies",
    estimatedValue: "$3,000 – $6,000",
    leadScore: 62,
    aiConfidence: 68,
    stage: "LOST",
    tags: ["agency", "marketing"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-05T07:30:00Z").toISOString(),
    updatedAt: new Date("2026-06-18T14:00:00Z").toISOString(),
  },
  {
    id: "10",
    workspaceId: "ws_1",
    company: "CloudNine Logistics",
    website: "cloudninelogistics.com",
    industry: "Logistics & Supply Chain",
    companySize: "51–200",
    country: "United States",
    city: "Chicago",
    contactName: "David Park",
    contactTitle: "VP of Technology",
    email: "david.park@cloudninelogistics.com",
    phone: "+1 312 555 0876",
    whatsapp: "+1 312 555 0876",
    linkedin: "linkedin.com/in/davidpark",
    painPoints: ["Real-time tracking gaps", "No driver communication platform", "Manual billing"],
    icebreaker: "CloudNine's 2-day delivery guarantee across the Midwest is incredibly impressive.",
    outreachAngle: "Real-time shipment tracking dashboard with automated driver notifications",
    estimatedValue: "$25,000 – $60,000",
    leadScore: 90,
    aiConfidence: 93,
    stage: "WHATSAPP_SENT",
    tags: ["logistics", "enterprise", "high-value"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-23T14:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-26T07:00:00Z").toISOString(),
  },
  {
    id: "11",
    workspaceId: "ws_1",
    company: "EduPath Learning",
    website: "edupathlearning.com",
    industry: "EdTech",
    companySize: "11–50",
    country: "United States",
    city: "Boston",
    contactName: "Rachel Kim",
    contactTitle: "Head of Product",
    email: "rachel@edupathlearning.com",
    phone: "+1 617 555 0543",
    whatsapp: "+1 617 555 0543",
    linkedin: "linkedin.com/in/rachelkim",
    painPoints: ["Student drop-off rate", "No personalized learning paths", "Manual grading"],
    icebreaker: "EduPath's adaptive quiz engine just won the EdTech Breakthrough Award — congrats!",
    outreachAngle: "AI-powered student engagement and personalized curriculum system",
    estimatedValue: "$10,000 – $22,000",
    leadScore: 83,
    aiConfidence: 86,
    stage: "NEW",
    tags: ["edtech", "ai"],
    source: "AI_FINDER",
    isArchived: false,
    createdAt: new Date("2026-06-25T15:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-25T15:00:00Z").toISOString(),
  },
];

export const mockLeadSparklineData = [4, 7, 5, 12, 8, 15, 10, 18, 14, 22, 17, 28];
