import type { Proposal } from "@/lib/types";

export const mockProposals: Proposal[] = [
  {
    id: "p1",
    workspaceId: "ws_1",
    leadId: "8",
    title: "AI-Powered Lead Nurturing System for Coastal Property Group",
    status: "ACCEPTED",
    projectType: "Web Application",
    budget: "$12,000",
    timeline: "8 weeks",
    requirements:
      "Need a CRM-integrated lead nurturing system with automated follow-ups, agent performance tracking, and real-time analytics.",
    content: {
      title: "AI-Powered Lead Nurturing System for Coastal Property Group",
      introduction:
        "Dear Roberto,\n\nThank you for considering our services for Coastal Property Group's digital transformation. Having reviewed your current operations and the challenges your agents face with manual lead follow-up, I'm excited to present a comprehensive solution that will transform how your team converts leads into closed deals.\n\nCoastal Property Group's reputation for premium waterfront properties in Brickell is exceptional. The opportunity to scale that success with AI-powered automation is significant — and the timing couldn't be better as Miami's luxury market continues to surge.\n\nThis proposal outlines a complete lead nurturing ecosystem that will automate your follow-up sequences, provide your agents with real-time lead intelligence, and deliver the analytics clarity you need to make data-driven decisions.",
      problemAnalysis:
        "Based on our discovery conversation, Coastal Property Group faces three core challenges: (1) Manual lead follow-up causing 68% of warm leads to go cold within 48 hours, (2) No centralized CRM leading to agents duplicating efforts and losing track of conversations, and (3) Agent conversion rate significantly below the Miami luxury market benchmark of 4.2%.",
      proposedSolution:
        "We will build a custom AI-powered CRM and lead nurturing platform specifically designed for luxury real estate. The system will automatically follow up with leads via email and SMS, score leads based on engagement, and route hot leads to your top-performing agents in real time.",
      scopeOfWork: [
        "Custom CRM dashboard with drag-and-drop pipeline management",
        "AI lead scoring engine (0–100 score based on 14 behavioral signals)",
        "Automated email + SMS follow-up sequences (up to 8 touchpoints)",
        "Agent performance analytics with individual KPIs",
        "Lead source attribution and ROI tracking",
        "WhatsApp Business API integration for instant notifications",
        "Mobile-responsive agent app (PWA)",
      ],
      deliverables: [
        "Fully functional CRM web application",
        "iOS/Android-compatible PWA for agents",
        "Admin dashboard for Roberto",
        "3 pre-built nurture sequence templates",
        "90-day post-launch support",
        "Training documentation + video walkthroughs",
      ],
      timeline: [
        {
          phase: "Discovery & Design",
          duration: "Week 1–2",
          tasks: ["Requirements deep-dive", "UI/UX wireframes", "Database architecture", "Agent interviews"],
        },
        {
          phase: "Core Development",
          duration: "Week 3–5",
          tasks: ["CRM foundation", "Lead scoring engine", "Email automation", "SMS integration"],
        },
        {
          phase: "Advanced Features",
          duration: "Week 6–7",
          tasks: ["Analytics dashboard", "WhatsApp integration", "Agent PWA", "Admin controls"],
        },
        {
          phase: "Testing & Launch",
          duration: "Week 8",
          tasks: ["QA & bug fixes", "Team training", "Data migration", "Go-live"],
        },
      ],
      pricing: {
        packages: [
          {
            name: "Starter",
            price: 8000,
            features: [
              "CRM for up to 10 agents",
              "3 nurture sequences",
              "Basic analytics",
              "Email automation",
              "30-day support",
            ],
          },
          {
            name: "Professional",
            price: 12000,
            recommended: true,
            features: [
              "CRM for up to 25 agents",
              "Unlimited nurture sequences",
              "Advanced analytics + AI insights",
              "Email + SMS + WhatsApp automation",
              "Agent PWA",
              "Lead scoring engine",
              "90-day support",
            ],
          },
          {
            name: "Enterprise",
            price: 20000,
            features: [
              "Unlimited agents",
              "Custom AI model fine-tuning",
              "White-label option",
              "API access",
              "Dedicated account manager",
              "1-year support + 4 quarterly reviews",
            ],
          },
        ],
      },
      milestones: [
        { name: "Project Kickoff", percentage: 30, amount: 3600 },
        { name: "Core Development Complete", percentage: 40, amount: 4800 },
        { name: "Final Delivery & Launch", percentage: 30, amount: 3600 },
      ],
      technologies: ["Next.js 15", "TypeScript", "PostgreSQL", "Prisma ORM", "Resend (Email)", "Twilio (SMS)", "WhatsApp Business API", "Vercel"],
      terms: [
        "Payment due within 7 days of each milestone",
        "Source code delivered upon final payment",
        "Revisions: up to 3 rounds per phase included",
        "Client provides access to existing tools/data within 3 business days of kickoff",
        "Hosting and third-party API costs are client's responsibility",
      ],
      closing:
        "Roberto, I'm confident this system will increase your team's conversion rate by at least 40% within the first 90 days. I'd love to schedule a 30-minute call this week to walk through the proposal and answer any questions. Looking forward to building something exceptional together.",
    },
    shareToken: "shr_coastal_pg_2026",
    isPublic: true,
    viewCount: 4,
    createdAt: new Date("2026-06-10T09:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-15T14:00:00Z").toISOString(),
    expiresAt: new Date("2026-07-10T09:00:00Z").toISOString(),
  },
  {
    id: "p2",
    workspaceId: "ws_1",
    leadId: "6",
    title: "Shopify Automation Suite for Luxe Threads",
    status: "SENT",
    projectType: "Shopify Development",
    budget: "$9,000",
    timeline: "6 weeks",
    requirements: "Custom Shopify automation for inventory sync, multi-currency, and returns management.",
    content: null,
    shareToken: "shr_luxe_threads_2026",
    isPublic: false,
    viewCount: 2,
    createdAt: new Date("2026-06-22T11:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-24T09:00:00Z").toISOString(),
    expiresAt: new Date("2026-07-22T11:00:00Z").toISOString(),
  },
  {
    id: "p3",
    workspaceId: "ws_1",
    leadId: "4",
    title: "EHR Integration Platform for MedSync Healthcare",
    status: "DRAFT",
    projectType: "API Development",
    budget: "$35,000",
    timeline: "16 weeks",
    requirements: "HIPAA-compliant integrations between MedSync platform and 3 major EHR systems.",
    content: null,
    shareToken: null,
    isPublic: false,
    viewCount: 0,
    createdAt: new Date("2026-06-25T16:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-25T16:00:00Z").toISOString(),
    expiresAt: null,
  },
  {
    id: "p4",
    workspaceId: "ws_1",
    leadId: "5",
    title: "Deal Flow & Portfolio Management Dashboard for Launchpad VC",
    status: "VIEWED",
    projectType: "Web Application",
    budget: "$22,000",
    timeline: "10 weeks",
    requirements: "Custom VC deal flow CRM with LP reporting and portfolio company dashboards.",
    content: null,
    shareToken: "shr_launchpad_vc_2026",
    isPublic: true,
    viewCount: 7,
    createdAt: new Date("2026-06-20T10:00:00Z").toISOString(),
    updatedAt: new Date("2026-06-26T08:00:00Z").toISOString(),
    expiresAt: new Date("2026-07-20T10:00:00Z").toISOString(),
  },
];
